### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by schriftgestalt** [mekkablue/TTControlInstructionsPalette#1]
```
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/__init__.py", line 1314, in callback_

 File "plugin.py", line 62, in update
   currentInstance = thisFont.currentTab.previewInstances

 File "GlyphsApp/GlyphsApp/__init__.py", line 11103, in Get_ShowInPreview

 File "GlyphsApp/GlyphsApp/__init__.py", line 1833, in __getitem__

 File "GlyphsApp/GlyphsApp/__init__.py", line 428, in _validate_idx

IndexError: list index 0 out of range 0

App:3.0.4-3108 Plugin:1.0.7-9
```

**Comment by mekkablue** [comment]
I don’t know how this can happen in the first place. But I am catching the error now.
